# Generated by Django 4.1.5 on 2023-02-10 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthenticationApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=350, null=True)),
                ('Image', models.ImageField(null=True, upload_to='0_Images/Product')),
                ('Description', models.TextField(null=True)),
            ],
        ),
    ]
