# Generated by Django 4.1.5 on 2023-02-10 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AuthenticationApp', '0002_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Image',
            new_name='ProductImg',
        ),
    ]
